#!/bin/bash

set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "Usage $0 <config path> <output csv path>" >&2
    echo "Example: $0 ~/.config/automatic-journal/config.json /tmp/my_repo/journal.csv" >&2
    exit 1
fi

csv_path=$2

dir=$(dirname "$(readlink -f "$0")")
cd "$dir"  # This is where the Pipfile is.

rm "$csv_path" || true
pipenv run python3 -m automatic_journal "$@"
lib/sort_journal "$csv_path"
lib/git_commit "$csv_path"
