#!/bin/bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage automatic_journal <yyyy-mm-dd>" >&2
    exit 1
fi

dir=$(dirname "$(readlink -f "$0")")
date=$1
path_out="$dir/results/journal-$date-$(date +%s).csv"
mkdir -p "$(dirname "$path_out")"

for provider_dir in "$dir/providers"/*; do
    echo "=== Running $provider_dir ===" >&2
    if [[ -f "$provider_dir/main" ]]; then
        "$provider_dir/main" "$date" >> "$path_out"
    elif [[ -f "$provider_dir/main.py" ]]; then
        pipenv run "$provider_dir/main.py" >> "$path_out"
    else
        echo "No main script found" >&2
    fi
done
