#!/bin/bash

set -euo pipefail

if [[ $# -ne 2 ]]; then
    echo "Usage $0 <config path> <output csv path>" >&2
    echo "Example: $0 ~/.config/automatic-journal/config.json /tmp/my_repo/journal.csv" >&2
    exit 1
fi

config_path=$1
csv_path=$2

dir=$(dirname "$(readlink -f "$0")")
cd "$dir"  # This is where the Pipfile is.

rm "$csv_path" || true
lib/call_providers "$config_path" "$csv_path"
lib/sort_journal "$csv_path"
lib/git_commit "$csv_path"
