#!/bin/bash

# https://github.com/python-poetry/poetry/issues/2179

set -euo pipefail

project_dir=$(dirname "$(readlink -f "$0")")
pushd "$project_dir" > /dev/null
python_path="$(poetry env info -p)/bin/python"
popd > /dev/null
"$python_path" -m automatic_diary.visualize "$@"
