#!/bin/bash

# https://github.com/python-poetry/poetry/issues/2179
start_dir=$(pwd)
project_dir=$(dirname "$(readlink -f "$0")")
cd "$project_dir" || exit 1
poetry run sh -c "cd '$start_dir' && python3 -m automatic_diary.visualize $@"
