#!/bin/bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage $0 <output csv path>" >& 2
    exit 1
fi

path_out=$1
repo_path="$(dirname "$path_out")"

echo "=== Committing repo $repo_path ===" >&2

cd "$repo_path"
if ! git --no-pager diff --cached --exit-code; then
    echo "Please unstage all files before committing new journal." >&2
    exit 1
fi
git add "$(basename "$path_out")"
git commit -m "journal.csv: Update $(date "+%Y-%m-%d %H:%M:%S %z")"
