#!/bin/bash

set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Usage $0 <output csv path>" >&2
    exit 1
fi

csv_path=$1

echo "=== Sorting $csv_path ===" >&2

sort --field-separator="," --key=1,1 -o "$1" "$1"
